### ISSUE TITLE
 invalid use of incomplete type: QPromiseConversionException in qpromise_p.h

### ISSUE THREAD

**Issue by bitflippersanonymous** [simonbrunel/qtpromise#44]
I get a compile error with GCC 9.1.0

qpromise_p.h:586:58: error: invalid use of incomplete type 'class QtPromise::QPromiseConversionException'
             throw QtPromise::QPromiseConversionException{};
                                                                ^
qpromise_p.h:34:7: note: forward declaration of 'class QtPromise::QPromiseConversionException'
class QPromiseConversionException;

qpromise_p.h is included by qpromise_exceptions.h which contains the full definition of QPromiseConversionException, so qpromise_p.h will always be read first.

**Comment by simonbrunel** [comment]
@bitflippersanonymous I'm not sure how I can test this version of GCC on Windows. It works with GCC 8.1.0, which is shipped with Qt as part of MinGW. How do you include QtPromise (`#include <QtPromise>`)?

A solution would be, as explained in [this comment](https://github.com/simonbrunel/qtpromise/pull/41#discussion_r518251187), to move the [`QPromiseError` alias](https://github.com/simonbrunel/qtpromise/blob/master/src/qtpromise/qpromiseexceptions.h#L72) at the end of the `qpromise_p.h` file, so we can remove [this include](https://github.com/simonbrunel/qtpromise/blob/master/src/qtpromise/qpromiseexceptions.h#L11) from `qpromiseexceptions.h`. Can you try this change and report if it works with GCC 9.1.0?

**Comment by bitflippersanonymous** [comment]
Yes, thank you that works.

I removed the QPromiseError alias, removed #include<qpromise_p.h> from qpromiseexceptions.h and moved #include<qpromiseexceptions.h> above qpromise_p.h in qpromise.h and now it compiles without errors.

[patch.txt](https://github.com/simonbrunel/qtpromise/files/5969297/patch.txt)

**Comment by dpurgin** [comment]
I can confirm that the patch works on Ubuntu 20 with gcc-9

**Comment by dpurgin** [comment]
I've submitted Ryan's patch in #45

**Comment by simonbrunel** [comment]
Thank you for the patch and the PR.
