### ISSUE TITLE
No .fail without .then?

### ISSUE THREAD

**Issue by pwuertz** [simonbrunel/qtpromise#14]
In contrast to the `QPromise::reject` promise that is being tested in `tst_fail`, regular non-void promises fail to compile `.fail` methods being attached directly to `p`:
```c++
auto p = QPromise<int>([&](
    const QPromiseResolve<int>& resolve,
    const QPromiseReject<int>& reject)
{
    resolve(42);
    reject(43);
});
p.fail([](int x) {
    Q_UNUSED(x);
});
```
```
...qtpromise/src/qtpromise/qpromise_p.h:604: error: no matching function for call to ‘QtPromisePrivate::PromiseData<int>::resolve()’
             promise->m_d->resolve();
             ^~~~~~~
```

If `.fail` is preceded by a dummy `.then` method, the fail works:
```c++
p.then([](){}).fail([](int x) {
    Q_UNUSED(x);
});
```

**Comment by simonbrunel** [comment]
That's weird, it should work, maybe broken by fa987a50442e4b982864ce4e083f44e3c046e163 or 7b0cba5b9dab86d38de189091dfc954a4ad0ed8d. Does it work with 0.3?

**Comment by simonbrunel** [comment]
Could be related to `fail()` catching the same type as the promise value?

**Comment by simonbrunel** [comment]
Actually, `fail()` is supposed to recover an error and thus must return the "replacement" value required to continue the promise chain:

```cpp
auto p = QPromise<int>([&](auto resolve, auto reject)
{
    reject(43);
});

p.fail([](int x) {
    Q_UNUSED(x);
    return -1;
});
```

**Comment by pwuertz** [comment]
Oh, that makes sense. So just a misunderstanding on my part, thanks for clearing that up.

If I happen to find a good spot for a static_assert with a fitting message for such a mistake I'll let you know.
